"""Filter and score findings to reduce false positives and noise."""

import os
import re
from collections import defaultdict

SEVERITY_LEVELS = ["critical", "high", "medium", "low", "info"]

TEST_PATH_PATTERN = re.compile(
    r"(?:^|/)(?:test|tests|__tests__|spec|specs|testing|fixtures|mocks|stubs)(?:/|$)|"
    r"(?:^|/|_)(?:test_|spec_)[\w]+\.(?:py|js|ts|go|java|rb|rs)$|"
    r"(?:^|/)[\w]+(?:_test|_spec)\.(?:py|js|ts|go|java|rb|rs)$|"
    r"(?:^|/)[\w]+\.(?:test|spec)\.(?:py|js|ts|tsx|jsx|go|java|rb|rs)$"
)

GENERATED_PATH_PATTERN = re.compile(
    r"(?:^|/)(?:vendor|node_modules|dist|build|\.next|\.nuxt|out)(?:/|$)|"
    r"(?:\.generated\.|\.pb\.go|\.pb\.rs|_gen\.|\.min\.js|\.min\.css|\.bundle\.)"
)

GENERATED_COMMENT_PATTERNS = [
    re.compile(r"auto[- ]?generated", re.IGNORECASE),
    re.compile(r"do not edit", re.IGNORECASE),
    re.compile(r"generated by", re.IGNORECASE),
    re.compile(r"code generated", re.IGNORECASE),
    re.compile(r"@generated", re.IGNORECASE),
]

ENTRY_POINT_PATTERNS: dict[str, list[re.Pattern]] = {
    "python": [
        re.compile(r"@(?:app|router|bp|blueprint)\.(?:get|post|put|delete|patch|route)"),
        re.compile(r"def (?:main|handle_|serve_|api_)"),
        re.compile(r"class.*(?:View|APIView|Resource|Handler|Controller)\b"),
    ],
    "javascript": [
        re.compile(r"(?:app|router|server)\.(?:get|post|put|delete|patch|use)\s*\("),
        re.compile(r"export\s+(?:async\s+)?function\s+(?:handler|GET|POST|PUT|DELETE)"),
        re.compile(r"module\.exports\s*=\s*(?:async\s+)?function"),
    ],
    "java": [
        re.compile(r"@(?:Get|Post|Put|Delete|Patch|Request)Mapping"),
        re.compile(r"@(?:GET|POST|PUT|DELETE|PATCH)\s*\("),
        re.compile(r"public\s+\w+\s+(?:doGet|doPost|handle|process)"),
    ],
    "go": [
        re.compile(r"func\s+\w+\(\s*w\s+http\.ResponseWriter"),
        re.compile(r"\.(?:HandleFunc|Handle|Get|Post|Put|Delete)\s*\("),
        re.compile(r"func\s+\w+\(.*echo\.Context"),
    ],
}


def _reduce_severity(severity: str, levels: int = 1) -> str:
    try:
        idx = SEVERITY_LEVELS.index(severity)
    except ValueError:
        return severity
    return SEVERITY_LEVELS[min(idx + levels, len(SEVERITY_LEVELS) - 1)]


def is_test_code(file_path: str) -> bool:
    normalized = file_path.replace("\\", "/")
    return bool(TEST_PATH_PATTERN.search(normalized))


def is_generated_code(file_path: str) -> bool:
    normalized = file_path.replace("\\", "/")
    if GENERATED_PATH_PATTERN.search(normalized):
        return True
    return False


def is_generated_file_content(file_path: str, project_root: str) -> bool:
    full_path = os.path.join(project_root, file_path) if not os.path.isabs(file_path) else file_path
    if not os.path.isfile(full_path):
        return False
    try:
        with open(full_path, encoding="utf-8", errors="ignore") as f:
            head = "".join(f.readline() for _ in range(10))
    except OSError:
        return False
    return any(p.search(head) for p in GENERATED_COMMENT_PATTERNS)


def _detect_entry_points(file_content: str, language: str) -> list[int]:
    patterns = ENTRY_POINT_PATTERNS.get(language, [])
    lines = file_content.splitlines()
    entry_lines: list[int] = []
    for i, line in enumerate(lines, 1):
        for pat in patterns:
            if pat.search(line):
                entry_lines.append(i)
                break
    return entry_lines


def compute_reachability(
    finding: dict, project_root: str, file_cache: dict[str, str] | None = None,
) -> dict:
    file_path = finding.get("file", "")
    language = finding.get("language", "")
    finding_line = finding.get("start_line", 0)

    if not file_path or not language or not finding_line:
        return {"is_reachable": True, "confidence": "low", "reason": "insufficient_data"}

    if file_cache is not None and file_path in file_cache:
        content = file_cache[file_path]
    else:
        full_path = os.path.join(project_root, file_path) if not os.path.isabs(file_path) else file_path
        try:
            with open(full_path, encoding="utf-8", errors="ignore") as f:
                content = f.read()
            if file_cache is not None:
                file_cache[file_path] = content
        except OSError:
            return {"is_reachable": True, "confidence": "low", "reason": "file_not_readable"}

    entry_lines = _detect_entry_points(content, language)

    if not entry_lines:
        return {"is_reachable": True, "confidence": "low", "reason": "no_entry_points_detected"}

    # Check if the finding is inside a function/method that starts at an entry point
    # Simple heuristic: entry point at or before finding, within reasonable distance
    for ep_line in entry_lines:
        if ep_line <= finding_line <= ep_line + 100:
            return {"is_reachable": True, "confidence": "high", "reason": "inside_entry_point"}

    return {"is_reachable": False, "confidence": "medium", "reason": "not_near_entry_point"}


def apply_finding_filters(
    findings: list[dict],
    project_root: str,
    config: dict | None = None,
) -> list[dict]:
    if config is None:
        config = {}

    filter_config = config.get("finding_filters", {})
    test_config = filter_config.get("test_code", {})
    gen_config = filter_config.get("generated_code", {})
    reachability_config = filter_config.get("reachability", {})

    test_enabled = test_config.get("enabled", True)
    test_action = test_config.get("severity_reduction", "one_level")
    gen_enabled = gen_config.get("enabled", True)
    gen_action = gen_config.get("action", "suppress")
    reach_enabled = reachability_config.get("enabled", False)

    file_cache: dict[str, str] = {}
    result: list[dict] = []

    for f in findings:
        entry = dict(f)
        file_path = f.get("file", "")

        # Generated code filter
        if gen_enabled and (is_generated_code(file_path) or is_generated_file_content(file_path, project_root)):
            entry["context"] = "generated_code"
            if gen_action == "skip":
                continue
            entry["is_suppressed"] = True
            entry["suppression_reason"] = "generated_code"
            result.append(entry)
            continue

        # Test code filter
        if test_enabled and is_test_code(file_path):
            entry["context"] = "test_code"
            if test_action == "skip":
                continue
            entry["original_severity"] = f.get("severity", "info")
            entry["severity"] = _reduce_severity(f.get("severity", "info"))

        # Reachability scoring
        if reach_enabled and file_path and f.get("language"):
            entry["reachability"] = compute_reachability(f, project_root, file_cache)

        result.append(entry)

    return result
